### ISSUE TITLE
Problem with Python

### ISSUE THREAD

**Issue by JulianWgs** [weibeld/heroku-buildpack-graphviz#11]
Hello :)

I've added the following build packs:
1. heroku/python
2. https://github.com/weibeld/heroku-buildpack-graphviz

but the following command

```bash
heroku run dot -V                                                         
```
returns 
```
Running dot -V on ⬢ dask-log-server... up, run.4995 (Free)
bash: dot: command not found
```

What am I doing wrong?

Thanks in advance :)

**Comment by weibeld** [comment]
In case the problem still exists, could you give more input? Which Heroku stack are you using and what's the log output of the deploy?
