### ISSUE TITLE
Can't create image on Heroku

### ISSUE THREAD

**Issue by Alexspriet** [weibeld/heroku-buildpack-graphviz#15]
Hi,

First, thank you for your buildplack!

What is the best way to generate an image with GraphViz, then display it?
How it will look if we use it through tmp directory?

Cheers

**Comment by weibeld** [comment]
You can generate an image, for example, by directly invoking one of the Graphviz commands (see [here](https://graphviz.org/documentation/)) from your application. Then how you display it, depends entirely on the type of application you're running, e.g. a web application. In general, after you created an image, you can display it like any other image.
