### ISSUE TITLE
Doesn’t work in Japanese

### ISSUE THREAD

**Issue by yudukikun5120** [weibeld/heroku-buildpack-graphviz#16]
![image](https://user-images.githubusercontent.com/45707929/116692358-33711f80-a9f7-11eb-95cb-957fbbfc2d4d.png)

As the picture above, this buildpack does not work in Japanese.
You can re-examine this case in [this website](https://ubiregiinc.github.io/graphviz-server/index.html): the folk of this repository.

**Comment by weibeld** [comment]
In what character encoding is the Graphviz file saved (e.g. UTF-8)? And is there any difference if you use a different output format, e.g. SVG?
