### ISSUE TITLE
heroku-22 image?

### ISSUE THREAD

**Issue by vanities** [weibeld/heroku-buildpack-graphviz#17]
It would be great if we could have one!

Edit: looks like it only needs readme and repo url updates to get this working, I may have time this weekend to submit a PR

**Comment by vanities** [comment]
https://github.com/weibeld/heroku-buildpack-graphviz/pull/18 here you go :) Let me know if you want any changes

**Comment by PBorocz** [comment]
Thanks for doing this @vanities! Temporarily setting my buildpack to your repo instead of this one worked great...will be watching until @weibeld merges it into his master.

**Comment by weibeld** [comment]
@vanities Great, thanks for the PR!
@PBorocz Thanks for the reminder, the PR is merged now.
