### ISSUE TITLE
error while loading shared libraries: libgvc.so.6

### ISSUE THREAD

**Issue by sepulworld** [weibeld/heroku-buildpack-graphviz#5]
After including in buildpack and testing in Heroku console with ```dot -V``` it returns:

```dot: error while loading shared libraries: libgvc.so.6: cannot open shared object file: No such file or directory```

**Comment by sepulworld** [comment]
Here is what my app.json looks like:

```
{
  "name": "Terraform State of Awareness",
  "description": "A dashboard that helps centralize and monitor disparate Terraform states",
  "repository": "https://github.com/sepulworld/tfsoa",
  "keywords": ["terraform", "ruby", "sinatra"],
  "addons": ["heroku-postgresql:hobby-dev"],
  "image": "heroku/ruby",
  "buildpacks": [
    {
      "url": "https://github.com/weibeld/heroku-buildpack-graphviz.git"
    },
    {
      "url": "heroku/ruby"
    }
  ],
  "formation": {
    "web": {
      "quantity": 1,
      "size": "free"
    }
  },
  "scripts": {
    "postdeploy": "bundle exec rake db:migrate"
  }
}
```

**Comment by weibeld** [comment]
Thanks for pointing out the problem. The new Heroku-16 stack seems to miss some of the dependencies for Graphviz that were present in Cedar-14. That's why there was the `libgvc.so.6` error message. The buildpack has now been updated to install these dependencies on Heroku-16, so it should work now.

Please report if it works for you now.

**Comment by sepulworld** [comment]
I am able to get past this error now, thanks! 

```
dot - graphviz version 2.38.0 (20140413.2041)
```

However, looks like this Graphviz build doesn't support PNG? 

```Format: "png" not recognized```

**Comment by sepulworld** [comment]
Would you consider adding support for PNG?

**Comment by sepulworld** [comment]
Hmm, it doesn't seem to recognize any format I try so far:

dot -Tsvg
dot -Tpng

the list is recognizes is empty it appears:
<img width="928" alt="screen shot 2017-05-30 at 2 26 58 pm" src="https://cloud.githubusercontent.com/assets/538171/26605774/2870642c-4544-11e7-9771-438ea2192c2d.png">

**Comment by sepulworld** [comment]
It appears it isn't compiled properly?

when I run just ```dot``` on console


<img width="986" alt="screen shot 2017-05-30 at 2 28 33 pm" src="https://cloud.githubusercontent.com/assets/538171/26605828/66b36eb4-4544-11e7-8b54-aa1e414b6676.png">

**Comment by sepulworld** [comment]
Perhaps related to this reported deb installer bug in 2.36? https://askubuntu.com/questions/503567/dot-doesnt-recognize-any-formats

But, I did verify that via dot -V that 2.38 is installed.

**Comment by weibeld** [comment]
The problem seems to be solved when running `dot -c`. This creates the necessary config file to enable all the plugins. I added this to the buildpack. Can you please test it now?

**Comment by sepulworld** [comment]
Thanks! 👍  confirmed it works now. I appreciate the buildpack and the help!

**Comment by seigel** [comment]
Quick question, how do I update huginn in place on heroku and will I lose data?
Thanks!
