### ISSUE TITLE
ExecutableNotFound appearing during dot run

### ISSUE THREAD

**Issue by amureki** [weibeld/heroku-buildpack-graphviz#6]
Hey @weibeld,

We've experiencing some issues with using graphviz buildpack since two days.
I'm assuming this related to commit https://github.com/weibeld/heroku-buildpack-graphviz/commit/8054a8ef7ce41952a54e6d55a6652509ba08dc8d.

Part of the traceback:
```
Exception occurred:
  File "/app/.heroku/python/lib/python3.6/site-packages/graphviz/backend.py", line 126, in render
    raise ExecutableNotFound(args)
graphviz.backend.ExecutableNotFound: failed to execute ['dot', '-Tsvg', '-O', '/tmp/tmpq4eo0c0j/accommodation'], make sure the Graphviz executables are on your systems' PATH
```

I will try to investigate more, but maybe you already have an idea about what could be wrong here.

And many thanks for package!

**Comment by weibeld** [comment]
Hey, yes I made a backward-incompatible change in commit 8054a8ef7ce41952a54e6d55a6652509ba08dc8d. The Graphviz executables are now in `/app/heroku-buildpack-graphviz/usr/bin` and not anymore in `/app/graphviz/bin`.

But the error is still strange, as the directory of `dot` should still be in the `PATH`.

So, the following information would be helpful:

1) Which stack are you using, Cedar-14 or Heroku-16? (Run `heroku stack`)
2) What's the output of `heroku run echo $PATH`?

**Comment by amureki** [comment]
@weibeld thank you for fast answer! 
1. Current stack is Cedar-14 there, but we initialised update to Heroku-16, which should be applied for the next deploy (which is failing because of this bug 😅).
2. During deploy, echo $(PATH) is showing this:
```
/app/graphviz/bin:/app/.heroku/python/bin:/app/.heroku/vendor/bin::/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/tmp/codon/vendor/bin:/app/tmp/buildpacks/c19e1b360ea9390d706eff64ca53391e03bd1c956a8baea44d4959d8ec7ba61280ebf5df63f342b59715878286e3719fc9be7cf3f61c0fce183645cff5d3f8f9/vendor/bpwatch:/app/tmp/buildpacks/c19e1b360ea9390d706eff64ca53391e03bd1c956a8baea44d4959d8ec7ba61280ebf5df63f342b59715878286e3719fc9be7cf3f61c0fce183645cff5d3f8f9/vendor/pip-pop
```
So this is still `/app/graphviz/bin` there...

P.S. Now I am realising, that it could be because of one of our custom sphinx buildpacks and I need to check it...

**Comment by amureki** [comment]
So, @weibeld the problem was in our sphinx buildpack was setting PATH without respecting new executables directory.

Thank you for helping anyways!
