### ISSUE TITLE
error while loading shared libraries: libgvc.so.6

### ISSUE THREAD

**Issue by amureki** [weibeld/heroku-buildpack-graphviz#9]
Hi @weibeld ,

I am using this buildpack and noticed that I am getting this error:

```
[stderr]
b'dot: error while loading shared libraries: libgvc.so.6: cannot open shared object file: No such file or directory\n'
[stdout]
b''
```

I checked an old issue: https://github.com/weibeld/heroku-buildpack-graphviz/issues/5 but did not find it helpful in my current setup:

Heroku-18
Graphviz 2.40.1

Do you think, that this is a Heroku-18 stack issue and we should appeal to them?

Thanks,
Rust

**Comment by amureki** [comment]
I found this article in Heroku docs:
https://devcenter.heroku.com/articles/stack-packages and `libgvc6` is not stated in `heroku-18`. :(

**Comment by weibeld** [comment]
Hi, on which command do you get this error? If I run the buildpack for Heroku-18, the test command `heroku run dot -V` works correctly.

**Comment by amureki** [comment]
@weibeld `heroku run dot -V` also works perfectly here.

We are using Sphinx extension to draw a dependency graph:
https://www.sphinx-doc.org/en/master/usage/extensions/graphviz.html 
https://github.com/sphinx-doc/sphinx/blob/master/sphinx/ext/graphviz.py

Sadly the output is quite messy and I could not easily find yet which graphviz command is running there in the background:

```
WARNING: dot code 'digraph inheritance5ff8edd86e {\nrankdir=LR;\nsize="8.0, 12.0";\n  "MyMixin" ..........
[arrowsize=0.5,style="setlinewidth(0.5)"];\n}\n': dot exited with error:
[stderr]
b'dot: error while loading shared libraries: libgvc.so.6: cannot open shared object file: No such file or directory\n'
[stdout]
b''
```

**Comment by weibeld** [comment]
This shared library should be in `/app/heroku-buildpack-graphviz/usr/lib/x86_64-linux-gnu` and this directory should be set in the `LD_LIBRARY_PATH` environment variable. So, I'm not sure why Sphinx can't find it, while `dot` can find it wen you run `dot -V`.

**Comment by amureki** [comment]
Interesting, I did check, and everything is how you described.

Probably this question should be raised in Sphinx then...
